In [1]:
import pandas as pd
import numpy as np


data1=pd.read_csv('rank_count_1.csv')
df1 = pd.DataFrame(data1)

data3=pd.read_csv('rank_count_3.csv')
df3 = pd.DataFrame(data3)

data5=pd.read_csv('rank_count_5.csv')
df5 = pd.DataFrame(data5)

In [2]:
df1

df1['from'] = 'score 1'

temp = df1['rank'].sum()

   Unnamed: 0  rank  count     from
0          먹다     1     37  score 1
1          하다     2     87  score 1
2          있다     3     18  score 1
3          않다     4     25  score 1
4          소스     5      6  score 1
5         아니다     6     18  score 1
6          이다     7     27  score 1
7          보다     8     19  score 1
8          되다     9     14  score 1
9         맛있다    10     22  score 1
10        아쉽다    11      8  score 1
11        이렇다    12      6  score 1
12         알다    13      6  score 1
13         주문    14      5  score 1
14         좋다    15      9  score 1
15         넣다    16      5  score 1
16         기억    17      6  score 1
17         껍질    18      4  score 1
18         예약    19      4  score 1
19        되어다    20      2  score 1
20         지금    21      2  score 1
21         아내    22      2  score 1
22       어울리다    23      2  score 1
23         방법    24      2  score 1
24       다양하다    25      2  score 1
25         이집    26      8  score 1
26         많다    27      7  score 1
27         퍽퍽    28      3  score 1
28        게다가    29      5  score 1
29       평범하다    30      5  score 1
30         리뷰    31      5  score 1
31         없다    32     17  score 1
32         정말    33     13  score 1
33        괜찮다    34      9  score 1
34       레스토랑    35      7  score 1
35         와인    36      5  score 1
36         들다    37      6  score 1
37         같다    38     17  score 1
38         자다    39      7  score 1
39         주다    40     10  score 1

In [7]:


df3['from'] = 'score 3'

df3

   Unnamed: 0  rank  count     from
0         맛있다     1     46  score 3
1          하다     2     90  score 3
2          먹다     3     52  score 3
3         나오다     4     27  score 3
4          좋다     5     39  score 3
5          자다     6     15  score 3
6          살짝     7     10  score 3
7          메뉴     8     10  score 3
8          방문     9     19  score 3
9          없다    10     17  score 3
10         생각    11     13  score 3
11         있다    12     18  score 3
12        아쉽다    13     13  score 3
13         사실    14      5  score 3
14         같다    15     17  score 3
15         많다    16      8  score 3
16         알다    17      4  score 3
17        모르다    18      6  score 3
18        파스타    19     13  score 3
19         이다    20     20  score 3
20        아니다    21     23  score 3
21         주문    22     16  score 3
22         음식    23     15  score 3
23        아뮤즈    24      4  score 3
24        트러플    25      9  score 3
25         요리    26     22  score 3
26       좋아하다    27      8  score 3
27       레스토랑    28      4  score 3
28         들다    29     12  score 3
29        디저트    30     11  score 3
30         크다    31      5  score 3
31        익히다    32      4  score 3
32         않다    33     19  score 3
33         따다    34      4  score 3
34        만들다    35      2  score 3
35       당연하다    36      2  score 3
36         버섯    37      4  score 3
37         감흥    38      2  score 3
38         식감    39      8  score 3
39         작다    40      3  score 3

In [8]:


df5['from'] = 'score 5'

df5

   Unnamed: 0  rank  count     from
0          하다     1   1003  score 5
1          있다     2    465  score 5
2          먹다     3    654  score 5
3          좋다     4    474  score 5
4          않다     5    226  score 5
5          되다     6    180  score 5
6          보다     7    179  score 5
7         맛있다     8    564  score 5
8         아니다     9    113  score 5
9          메뉴    10    198  score 5
10         없다    11    184  score 5
11         같다    12    191  score 5
12         자다    13    140  score 5
13        나오다    14    184  score 5
14         싶다    15    122  score 5
15         들다    16    112  score 5
16         이다    17    255  score 5
17         소스    18    118  score 5
18         느낌    19    125  score 5
19         재료    20     84  score 5
20         주문    21     89  score 5
21         정도    22     94  score 5
22        되어다    23     59  score 5
23        느끼다    24     54  score 5
24         방문    25    142  score 5
25        만들다    26     50  score 5
26         버터    27     56  score 5
27       좋아하다    28     85  score 5
28         생각    29     95  score 5
29         가다    30    142  score 5
30         하나    31    143  score 5
31         요리    32    164  score 5
32         음식    33    122  score 5
33         새우    34     70  score 5
34         차다    35     33  score 5
35         살짝    36     59  score 5
36         식감    37     59  score 5
37         아주    38     70  score 5
38         주다    39     54  score 5
39         오다    40    102  score 5

In [12]:
df = pd.concat([df1,df3,df5], ignore_index=True)

df['from'].value_counts()

score 3    40
score 1    40
score 5    40
Name: from, dtype: int64

In [10]:
df.to_csv('rank_count_merge.csv')